import "./ItemDetails.css";
import RelationsPanel from "../RelationsPanel";
const names = { area: "Область", project: "Проект", task: "Задача", inbox: "Входящие", planned: "Запланировано", in_progress: "В работе", done: "Завершено", cancelled: "Отменено", low: "Низкий", normal: "Средний", high: "Высокий", critical: "Критический" };
const colors = [["slate", "Серо-синий"], ["blue", "Синий"], ["green", "Зелёный"], ["teal", "Бирюзовый"], ["amber", "Янтарный"], ["red", "Красный"], ["purple", "Фиолетовый"], ["gray", "Серый"]];
const sizes = [["small", "S", "Маленький — 56 px"], ["medium", "M", "Средний — 110 px"], ["large", "L", "Большой — 170 px"]];

export default function ItemDetails({ item, items, relations, workspaces, activeWorkspace, onCreateRelation, onDeleteRelation, isInToday, onAddToToday, onRemoveFromToday, onEdit, onAddChild, onOpen, onClose, style, display = {}, onDisplayChange, onAddToWorkspace, presenceRuleMode, onPresenceRuleChange }) {
  return <aside className="item-details" style={style} onPointerDown={(event) => event.stopPropagation()}>
    <header><div><span className="inspector-label">Информация</span><h2>{item.title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Закрыть">×</button></header>
    <dl><div><dt>Тип</dt><dd>{names[item.kind]}</dd></div><div><dt>Статус</dt><dd><i className="status-dot" />{names[item.status]}</dd></div><div><dt>Приоритет</dt><dd>{names[item.priority]}</dd></div><div><dt>Срок</dt><dd>{item.due_at || "—"}</dd></div></dl>{item.description && <p>{item.description}</p>}
    <span className="inspector-label">Быстрые действия</span><div className="item-details__actions"><button onClick={onAddChild}>＋ Дочерний</button><button onClick={onEdit}>Редактировать</button><button onClick={onOpen}>Открыть полностью</button>{item.kind === "task" && <button onClick={() => isInToday ? onRemoveFromToday(item.id) : onAddToToday(item.id)}>{isInToday ? "Убрать из Сегодня" : "В Сегодня"}</button>}{onAddToWorkspace && <button className="item-details__workspace-action" onClick={onAddToWorkspace}>В другое пространство</button>}</div>
    {onPresenceRuleChange && <div className="presence-settings"><span className="inspector-label">Присутствие в пространстве</span><select value={presenceRuleMode} onChange={(event) => onPresenceRuleChange(event.target.value)} aria-label="Правило присутствия"><option value="self">Только объект</option><option value="children">Объект и дети</option><option value="subtree">Всё поддерево</option></select></div>}
    <RelationsPanel item={item} items={items} relations={relations} workspaces={workspaces} activeWorkspace={activeWorkspace} onCreate={onCreateRelation} onDelete={onDeleteRelation} />
    {onDisplayChange && <div className="node-settings"><span className="inspector-label">Отображение объекта</span><div className="node-setting-row"><span>Размер</span><div className="size-options">{sizes.map(([value, label, title]) => <button key={value} type="button" title={title} aria-label={title} aria-pressed={(display.size ?? "medium") === value} onClick={() => onDisplayChange({ size: value })}>{label}</button>)}</div></div><div className="node-setting-row"><span>Цвет</span><div className="color-options">{colors.map(([value, label]) => <button key={value} type="button" className={`color-chip color-chip--${value}`} title={label} aria-label={label} aria-pressed={(display.color ?? "slate") === value} onClick={() => onDisplayChange({ color: value })} />)}</div></div></div>}
  </aside>;
}
